# Generated by Django 4.2.1 on 2023-09-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelTable(
            name='account',
            table='accounts',
        ),
    ]
