# Generated by Django 4.2.1 on 2023-05-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_content',
            field=models.FileField(upload_to='audio_files/'),
        ),
    ]
