# Generated by Django 4.2.1 on 2023-05-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_alter_audio_audio_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='borned_at',
            new_name='birth_date',
        ),
    ]
