# Generated by Django 4.2.1 on 2023-09-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='image',
            field=models.ImageField(null=True, upload_to='book-images'),
        ),
    ]
