# Generated by Django 4.2.1 on 2023-09-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_summary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='image',
            field=models.ImageField(upload_to='book-images'),
        ),
    ]
