# Generated by Django 4.2.1 on 2023-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0003_rename_borned_at_author_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('translated_phrase', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='summary',
            name='translated_text',
        ),
    ]
