# Generated by Django 4.2.1 on 2023-09-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0005_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='favorite',
        ),
        migrations.AlterModelTable(
            name='phrase',
            table='phrase',
        ),
        migrations.AlterModelTable(
            name='summary',
            table='summary',
        ),
        migrations.AlterModelTable(
            name='summarygender',
            table='summary_gender',
        ),
    ]
