# Generated by Django 4.2.1 on 2023-05-14 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='domain_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='last_time_checked',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 14, 18, 40, 0, 765211)),
        ),
    ]
