# Generated by Django 4.2.1 on 2023-09-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0003_alter_flashcard_phrase_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deck',
            table='decks',
        ),
        migrations.AlterModelTable(
            name='flashcard',
            table='flashcards',
        ),
    ]
